"""Increase password_hash length to 255

Revision ID: 0035a381a617
Revises: e4c589b5a036
Create Date: 2025-03-20 14:36:09.465770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0035a381a617'
down_revision = 'e4c589b5a036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint('activity_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['creator_id'], ['id'])

    with op.batch_alter_table('participation', schema=None) as batch_op:
        batch_op.drop_constraint('participation_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('participation_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'activity', ['activity_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               existing_nullable=False)

    with op.batch_alter_table('participation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('participation_ibfk_2', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('participation_ibfk_1', 'activity', ['activity_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('activity_ibfk_1', 'user', ['creator_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
